name: Release lib-version

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java for publishing
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
          server-id: github                 
          server-username: GITHUB_ACTOR    
          server-password: MAVEN_TOKEN      
          settings-path: ${{ github.workspace }}

      - name: Build & Publish
        run: mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml -DskipTests
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_DEPLOY_TOKEN }}
